"""changed column type for genres

Revision ID: cb9c07f7ba0b
Revises: cfe57c298cca
Create Date: 2024-09-05 14:57:35.039375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb9c07f7ba0b'
down_revision = 'cfe57c298cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
        batch_op.drop_column('genre')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
